// For description of these values see http://adblockplus.org/en/preferences

pref("extensions.adblockedge.currentVersion", "0.0");
pref("extensions.adblockedge.enabled", true);
pref("extensions.adblockedge.frameobjects", true);
pref("extensions.adblockedge.fastcollapse", false);
pref("extensions.adblockedge.showinstatusbar", false);
pref("extensions.adblockedge.detachsidebar", false);
pref("extensions.adblockedge.defaulttoolbaraction", 0);
pref("extensions.adblockedge.defaultstatusbaraction", 0);
pref("extensions.adblockedge.sidebar_key", "Accel Shift V, Accel Shift U");
pref("extensions.adblockedge.filters_key", "Accel Shift E, Accel Shift F, Accel Shift O");
pref("extensions.adblockedge.enable_key", "");
pref("extensions.adblockedge.flash_scrolltoitem", true);
pref("extensions.adblockedge.previewimages", true);
pref("extensions.adblockedge.data_directory", "adblockedge");
pref("extensions.adblockedge.patternsbackups", 5);
pref("extensions.adblockedge.patternsbackupinterval", 24);
pref("extensions.adblockedge.whitelistschemes", "about chrome file irc moz-safe-about news resource snews x-jsd addbook cid imap mailbox nntp pop data javascript moz-icon");
pref("extensions.adblockedge.subscriptions_autoupdate", true);
pref("extensions.adblockedge.subscriptions_listurl", "https://adblockplus.org/subscriptions2.xml");
pref("extensions.adblockedge.subscriptions_fallbackurl", "https://adblockplus.org/getSubscription?version=%VERSION%&url=%SUBSCRIPTION%&downloadURL=%URL%&error=%ERROR%&channelStatus=%CHANNELSTATUS%&responseStatus=%RESPONSESTATUS%");
pref("extensions.adblockedge.subscriptions_fallbackerrors", 5);
pref("extensions.adblockedge.documentation_link", "https://adblockplus.org/redirect?link=%LINK%&lang=%LANG%");
pref("extensions.adblockedge.savestats", false);
pref("extensions.adblockedge.composer_default", 2);
pref("extensions.adblockedge.clearStatsOnHistoryPurge", true);
pref("extensions.adblockedge.recentReports", []);
pref("extensions.adblockedge.hideContributeButton", false);
pref("extensions.adblockedge.blockableItemsSize", {width: 200, height: 200});
